# **Numpy Indexing and Selection**

In [5]:
import numpy as np

**Create an 2D array**

In [6]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Output will be :** 
                    **array([12, 13, 14, 15]**
                          **[17, 18, 19, 20])**
                          **[22, 23, 24, 25]**

---



In [12]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

**Output will be :** 
                    **array([2]**
                          **[7])**
                          **[12]**

In [21]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

**Output will be :** 
                    **array(**
                          **[21, 22, 23, 24, 25])**

In [25]:
arr[4:,:]

array([[21, 22, 23, 24, 25]])

**Output will be :** 
                    **array(**
                          **[16, 17, 18, 19, 20])**
                          **[21, 22, 23, 24, 25]**

In [26]:
arr[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Get the sum of all the values in arr**

In [27]:
np.sum(arr)

325

**Get the standard devition of the values in arr**

In [28]:
arr.std()

7.211102550927978

**get sum of all the columns in arr**

In [29]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])